# Database
quarkus.datasource.db-kind=postgresql
quarkus.datasource.devservices.image-name=postgres:18.2-alpine
quarkus.hibernate-orm.database.default-schema=sampleschema
quarkus.hibernate-orm.schema-management.strategy=validate

# Flyway
quarkus.flyway.migrate-at-start=true
quarkus.flyway.create-schemas=true
quarkus.flyway.schemas=sampleschema
quarkus.flyway.default-schema=sampleschema

# Logging Level
quarkus.log.level=${LOG_LEVEL:INFO}

# Analytics
quarkus.analytics.disabled=true
