# Database
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USERNAME}
quarkus.datasource.password=${DB_PASSWORD}

quarkus.datasource.jdbc.url=${DB_URL}
quarkus.datasource.jdbc.max-size=16
quarkus.hibernate-orm.database.default-schema=sampleschema
quarkus.hibernate-orm.schema-management.strategy=validate

# Flyway
quarkus.flyway.migrate-at-start=true
quarkus.flyway.create-schemas=true
quarkus.flyway.schemas=sampleschema
quarkus.flyway.default-schema=sampleschema

# Port and Host
quarkus.http.port=${PORT:8080}

# Logging Level
quarkus.log.level=${LOG_LEVEL:INFO}

# Analytics
quarkus.analytics.disabled=true