# Database
quarkus.datasource.db-kind=postgresql
quarkus.datasource.devservices.image-name=postgres:18.2-alpine

quarkus.hibernate-orm.database.default-schema=papertrailbot
quarkus.hibernate-orm.schema-management.strategy=validate

# Flyway
quarkus.flyway.migrate-at-start=true
quarkus.flyway.create-schemas=true
quarkus.flyway.schemas=papertrailbot
quarkus.flyway.default-schema=papertrailbot

# Redis
quarkus.cache.type=redis
quarkus.redis.devservices.image-name=redis:8.6.1-alpine

# Redis Cache Settings
quarkus.cache.redis."auditLog".ttl=30D
quarkus.cache.redis."messageLog".ttl=30D


# Logging Level
quarkus.log.level=INFO
quarkus.log.category."io.github.eggy03.papertrail.api.service".level=${LOG_LEVEL:INFO}

# Analytics
quarkus.analytics.disabled=true
